### ISSUE TITLE
Escalus - basic example issues (not sure if related to #130)

### ISSUE THREAD

**Issue by elixirLA** [esl/escalus#148] opened 2017-06-25 18:31 UTC
hi, just trying the basic example (and fixed the config file per issue #130 and also created the users alice, bob, carol, .... on localhost) but getting the following error:

`** exception exit: undef
     in function  fusco_cp:start_link/3
        called as fusco_cp:start_link({"localhost",5280,false},
                                      [{on_connect,
                                        #Fun<escalus_bosh.1.18338422>}],
                                      2)
     in call from escalus_bosh:init/1 (/home/ubuntu/escalus/_build/default/lib/escalus/src/escalus_bosh.erl, line 325)
     in call from gen_server:init_it/6 (gen_server.erl, line 328)
     in call from proc_lib:init_p_do_apply/3 (proc_lib.erl, line 240)`

**Comment by fenek** [comment] 2017-06-26 11:38
Hi @elixirLA 

Thanks for finding this issue. I've found the cause and I'm fixing it right now.

**Comment by fenek** [comment] 2017-06-26 11:54
Please check if branch https://github.com/esl/escalus/pull/149 works for you. :)

**Comment by erszcz** [comment] 2017-12-28 11:57
#149 was merged and closed a long time ago. @elixirLA please reopen this issue if you are still experiencing problems regarding it - I'm closing it now.

**Closed by erszcz** 2017-12-28 11:57 UTC
